---
title: "CV"
---


You can download pdf version of my CV:

<a href="CV.pdf" class="download" title="Download CV as PDF">Download full CV</a>

<a href="CV.pdf" class="download" title="Download CV as PDF">Download 1-page CV</a>

# CURRENT PROJECTS (2016-2017)

* Nanoscale IR spectroscopy of carbon nanotubes - evaluation of spectroscopic and imaging results
* Comparison of workflows for open source solutions for IR spectroscopy data sets processing: R Studio/Shiny and Orange (Python)
* Building Shiny interface for user-friendly IR spectra viewer for ISMI beamline


# Recent Conferences (2016-2017)


* 1st RCM of the project
* FTIR Workshop Berlin
* 9th International Workshop on Infrared Microscopy and Spectroscopy with Accelerator-Based Sources (WIRMS), Worcester College, Oxford, UK, 25-28.09.2017
* 52th Zakopane School of Physics, Zakopane, Poland, 22-27.05.2017
* 1st Infrared Spectroscopy and MIcroscopy(ISMI) beam-line workshop, Stephen Riady Centre UTown NUS, Singapore, 23.02.2017
* 13th International Conference on Atomically Controlled Surfaces, Interfaces and Nanostructures, Frascati, Italy, 9-15.10.2016 
* 13th International School and Symposium on Synchrotron Radiation in Natural Science, Ustron-Jaszowiec, Poland, 13-18.06.2016
* 4th Singapore Synchrotron Light Source Users' Meeting, NUS University Hall, Singapore, 29.02.2016

# Recent Papers (2016-2017)

1.    Banas, K., Banas, A., Heussler, S. P. and Breese, M. B. H. Influence of spectral resolution, spectral range and signal-to-noise ratio of Fourier transform infra-red spectra on identification of high explosive substances Spectrochimica Acta Part A: Molecular and Biomolecular Spectroscopy, 2018(188C), pp. 106-112
2.  Banas, A., Banas, K., Kalaiselvi, S. M. P., Pawlicki, P., Kwiatek, W. M. and Breese M B, H Is it possible to find presence of lactose in pharmaceuticals? — Preliminary studies by ATR-FTIR spectroscopy and chemometrics Spectrochimica Acta Part A: Molecular and Biomolecular Spectroscopy Volume 171, 15 January 2017, Pages 280–286, 2017, Vol. 171, pp. 280–286
3. McDonald, G., Tavakkoli, E., Cozzolino, D., Banas, K., Derrien, M. and Rengasamy, P. Field survey of total and dissolved organic carbon in alkaline soils of southern Australia: effect of pH and land management Soil Research, 2016

   
 
# Previous Conferences (2008-2015)

* 8th International Workshop on Infrared Microscopy and Spectroscopy with Accelerator-Based Sources (WIRMS), Riverhead, NJ, USA, 11-15.10.2015 
* 50th Zakopane School of Physics, Zakopane, Poland, 18-23.05.2015
* National Soil Science Conference, MCG, Melbourne, Australia, 23-27.11.2014
* 8th Asia Oceania Forum for Synchrotron Radiation Research (AOFSRR), National Synchrotron Radiation Research Center, Hsinchu, Taiwan, 15-17.09.2014
* 8th SPEC - Shedding New Light on Disease, Krakow, Poland, 17-22.08.2014
* 7th International Workshop on Infrared Microscopy and Spectroscopy with Accelerator-Based Sources (WIRMS), Lorne, Australia, 10-14.11.2013
* 7th Asia Oceania Forum for Synchrotron Radiation Research (AOFSRR), Himei, Japan, 21-24.09.2013
* 11th International School and Symposium on Synchrotron Radiation in Natural Science (ISSRNS), Tyniec, Poland, 20-25.05.2012
* X-ray Technology and Phase Contrast Imaging Workshop, SIMTech Auditorium, NTU, Singapore, 02.11.2011
* 6th International Workshop on Infrared Microscopy and Spectroscopy with Accelerator-Based Sources (WIRMS), Trieste, Italy 4-8.09.2011
* International Conference on Materials for Advanced Technologies (ICMAT), Suntec Convention Centre, Singapore 26.06-01.07.2011
* La Trobe-NUS Workshop on Synchrotron and Nanoscale Science, NUS, Singapore, 23.06.2011
* 7th International Conference on Synchrotron Radiation in Materials Science (SRMS), Oxford, UK, 11-14.07.2010
* 4th Materials Research Society of Singapore (MRS-S) Conference on Advanced Materials, IMRE, Singapore, 17-19.03.2010
* Internation Network of Younf Scientists Workshop, Engineering Faculty NUS, Singapore, 2-5.07.2009
* 3rd SSLS Synchrotron Radiation Workshop and Users' Meeting, Safra Mount Faber, Singapore, 19.11.2009
* 2nd SSLS Synchrotron Radiation Workshop and Users' Meeting, Discovery Theatrette at Biopolis, Singapore, 21.11.2008


# Previous Papers

1. paper 1
2. paper 2
3. paper 3
4. paper 4